name: dnevnik
description: "A private bilingual diary built with Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  archive: ^4.0.9
  cupertino_icons: ^1.0.9
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_quill: 11.5.1
  intl: 0.20.2
  path_provider: ^2.1.6
  pdf: 3.13.0
  printing: 5.15.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  xml: ^7.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/PTSerif-Regular.ttf
    - assets/fonts/PTSerif-Bold.ttf
    - assets/fonts/PTSerif-Italic.ttf
    - assets/fonts/PTSerif-BoldItalic.ttf
